/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto01_castañeda_dahan_gonzalez;

import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author USUARIO
 */
public class Vista_Grafo extends javax.swing.JFrame {

    /**
     * Creates new form Vista_Grafo
     */
    private Grafo grafo; 
    private int cantHormigas;
    private int cantIteraciones;
    private int ciudades;
    private double a,b,r;
    private Hormiga vectorHor[];
    private String cantH;
    public Vista_Grafo() {
        initComponents();
        this.setTitle("Simulador del Algoritmo de la Colonia de Hormigas");
//        this.setLocationRelativeTo(null);
        
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setResizable(false);
        this.setSize(1141,628);
        this.IniciarSimu.setVisible(false);
        this.verGraph.setVisible(false);
        this.NextIteracion.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        numHormiga = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        distReco = new javax.swing.JTextField();
        cuidadVisi = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        IniciarSimu = new javax.swing.JButton();
        NextIteracion = new javax.swing.JButton();
        verGraph = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        Salir = new javax.swing.JButton();
        IngresarVal = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextField2 = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 897, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        numHormiga.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 12)); // NOI18N
        numHormiga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numHormigaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Microsoft JhengHei Light", 1, 14)); // NOI18N
        jLabel1.setText("Información de la Corrida");

        jLabel2.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 12)); // NOI18N
        jLabel2.setText("Hormiga que realiza el recorrido");

        distReco.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 12)); // NOI18N
        distReco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                distRecoActionPerformed(evt);
            }
        });

        cuidadVisi.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 12)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 12)); // NOI18N
        jLabel3.setText("Distancia Recorrida");

        jLabel4.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 12)); // NOI18N
        jLabel4.setText("Cuidades Visitadas");

        IniciarSimu.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 12)); // NOI18N
        IniciarSimu.setText("Iniciar Simulación");
        IniciarSimu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IniciarSimuActionPerformed(evt);
            }
        });

        NextIteracion.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 12)); // NOI18N
        NextIteracion.setText("Siguiente Iteración");
        NextIteracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextIteracionActionPerformed(evt);
            }
        });

        verGraph.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 12)); // NOI18N
        verGraph.setText("Ver Mapa");
        verGraph.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verGraphActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NextIteracion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cuidadVisi, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(numHormiga, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(distReco)
                    .addComponent(IniciarSimu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(verGraph, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(4, 4, 4)
                .addComponent(numHormiga, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(1, 1, 1)
                .addComponent(distReco, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cuidadVisi, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(IniciarSimu, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(verGraph, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NextIteracion, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));

        jButton1.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 12)); // NOI18N
        jButton1.setText("Ir al Inicio");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Salir.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 12)); // NOI18N
        Salir.setText("Salir del Simulador");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });

        IngresarVal.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 12)); // NOI18N
        IngresarVal.setText("Ingresar Valores");
        IngresarVal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresarValActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Salir, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                    .addComponent(IngresarVal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(IngresarVal, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Salir, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
        );

        jPanel6.setBackground(new java.awt.Color(204, 204, 204));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 133, Short.MAX_VALUE)
        );

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Cantidad de Hormigas");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Distancia recorrida por cada Hormiga y orden de las ciudades");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Menor distancia recorrida y orden de las ciudades");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Cantidad de  feromonas por camino");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Camino más corto y distancia correspondiente");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jLabel6)
                .addGap(2, 2, 2)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jLabel8)
                .addGap(2, 2, 2)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jLabel9)
                .addGap(1, 1, 1)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(198, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 35, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1156, 1156, 1156))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(247, 247, 247))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 616, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IngresarValActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresarValActionPerformed
        // TODO add your handling code here:
        /*
        Creamos el grafo o mapa con la cantidad de cuidades indicadas por el usuario
        */

        int fila, columna;
        int val=0;

        boolean aux = true;
        boolean aux3 = true;
        boolean aux4 = true;
        boolean aux5 = true;
        boolean aux6 = true;
        int cantHormig, cantIte, validacion;
        //Le pedimos al usuario la cantida de hormigas
        String cantHorInt = JOptionPane.showInputDialog("Introduzca la cantidad de Hormigas");
        int dis=0;
        //Validamos que el usuario haya indicado un número de hormigas
        do{
            String obtHormigas =cantHorInt ;
            this.cantH=obtHormigas;
            if (obtHormigas!=null && obtHormigas.length()>0){
                try {
                    cantHormig = Integer.parseInt(cantHorInt);

                } catch (NumberFormatException e){
                    String erroCantH = JOptionPane.showInputDialog("ERROR! Introduzca una cantidad de hormigas válida");
                    this.cantH= erroCantH;
                    cantHorInt = erroCantH;
                    cantHormig = Integer.parseInt(cantHorInt);
                } finally{
                    aux4 = false;
                }
            } else{
                String errorCantH = JOptionPane.showInputDialog("ERROR! Introduzca la cantidad de hormigas");
                this.cantH= errorCantH;
                cantHorInt = errorCantH;
                cantHormig = Integer.parseInt(cantHorInt);
            }

        }while(aux4);
        

        this.cantHormigas = cantHormig;
        //Pedimos la cantidad de ciudades

        Integer [] cantCiuInt = {4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20};
        int cantCiudades = JOptionPane.showOptionDialog(null, "Seleccione la cantidad de ciudades deseada",
            "Click a button",
            JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE, null,cantCiuInt , cantCiuInt[0]);
        System.out.println(cantCiudades);
        //De acuerdo a lo que haya elegido el usuario se lo asignamos a las ciudades
        if(cantCiudades!=JOptionPane.CLOSED_OPTION){
            ciudades = cantCiudades + 4;
        } else {
            ciudades = 4;
        }

        grafo = new Grafo(ciudades);

        //Pedimos la cantidad de iteraciones

        String cantIteInt = JOptionPane.showInputDialog("Introduzca la cantidad de iteraciones");

        //Validamos que el usuario haya indicado la cantidad  de iteraciones
        do{
            String obtIte =cantIteInt ;
            if (obtIte!=null || obtIte.length()>0){
                try {
                    cantIte = Integer.parseInt(cantIteInt);

                } catch (NumberFormatException e){
                    String erroCantI = JOptionPane.showInputDialog("ERROR! Introduzca la cantidad de iteraciones válida");
                    cantIteInt = erroCantI;
                    cantIte = Integer.parseInt(cantIteInt);
                } finally{
                    aux5 = false;
                }
            } else{
                String errorCantI = JOptionPane.showInputDialog("ERROR! Introduzca la cantidad de iteraciones");
                cantIteInt = errorCantI;
                cantIte = Integer.parseInt(cantIteInt);
            }

        }while(aux5);

        cantIteraciones = cantIte;
        //Pedimos los valores de Alpha, Beta y Ro
        String Alpha =JOptionPane.showInputDialog("Introduzca un valor para la constante Alfa (valor recomendado 1)");

        //Validamos que el usuario haya indicado la cantidad  de alfa, beta y ro
        double valorAlpha=0;

        String alfaJF = Alpha;
        if(alfaJF==null){
            String errorCantAlpha1 = JOptionPane.showInputDialog("ERROR! Introduzca un valor para la constante alfa");
            Alpha = errorCantAlpha1;
        }
        if(alfaJF!=null){
            try{
                valorAlpha = Double.parseDouble(Alpha);
            }catch(NumberFormatException e){
                String errorCantAlpha = JOptionPane.showInputDialog("ERROR! Introduzca un valor valido para la constante alfa ");
                Alpha= errorCantAlpha;
                valorAlpha = Double.parseDouble(Alpha);
            }
        }
        this.a = valorAlpha;

        //Valor de beta
        double valorBeta=0;
        String Beta =JOptionPane.showInputDialog("Introduzca un valor para la constante Beta (valor recomendado 1)");
        String betaJF=Beta;
        if(betaJF==null){
            String errorCantBeta = JOptionPane.showInputDialog("ERROR! Introduzca un valor para la constante beta");
            Beta=errorCantBeta;
        }
        if(betaJF!=null){
            try{
                valorBeta = Double.parseDouble(Beta);
            } catch(NumberFormatException e){
                String errorCantBeta2 = JOptionPane.showInputDialog("ERROR! Introduzca un valor valido para la constante beta ");
                Beta = errorCantBeta2;
                valorBeta = Double.parseDouble(Beta);
            }
        }

        this.b=valorBeta;

        //Valor de Ro
        String Ro =JOptionPane.showInputDialog("Introduzca un valor para la constante RO (valor recomendado 0,5)");
        double valorRo=0;

        String roJF=Ro;
        if(roJF==null){
            String errorCantRo = JOptionPane.showInputDialog("ERROR! Introduzca un valor para la constante ro");
            Ro=errorCantRo;
        }
        if(betaJF!=null){
            try{
                valorRo = Double.parseDouble(Ro);
            } catch(NumberFormatException e){
                String errorCantRo2 = JOptionPane.showInputDialog("ERROR! Introduzca un valor valido para la constante ro ");
                Ro=errorCantRo2;
                valorRo = Double.parseDouble(Ro);
            }
        }

        this.r = valorRo;

        //Recorremos el grafo para indicar el nombre del las ciudades

        for(int i= 1; i<=ciudades;i++){
            do{

                String name = JOptionPane.showInputDialog("Ingrese el nombre de la ciudad "+ i +" "
                    + " ");
                //                Validamos si el usuario ha introducido un nombre
                if (name!=null && name.length()>0){
                    grafo.agregarCiudad(name);
                    aux = false;
                } else{
                    String nombre = JOptionPane.showInputDialog("ERROR! Por favor ingrese un nombre");
                    name = nombre;
                }
            } while(aux);
        }

        //        Agregar distancias
        validacion = 0;
        for (int i = ciudades; i>= 1 ; i--) {
            for (int j = i-1; j>=1; j--) {
                System.out.println("filas"+ i+ " columnas "+ j);
                System.out.println("filas"+ (i-1) + " columnas "+ (j-1));
                do{
                    validacion = 0;
                    String obtDis = JOptionPane.showInputDialog("Ingrese la distancia entre la ciudad"
                        + " "+ i + " "+ "y la ciudad "+ j +" " );
                    try{
                        dis = Integer.parseInt(obtDis);

                    } catch(NumberFormatException e){
                        validacion=-1;
                        JOptionPane.showMessageDialog(null,"ERROR! Por favor introduzca un valor numérico");

                    }
                }while(validacion==-1);
                fila = i;
                columna = j;
                grafo.agregarDistancias(dis, (i-1), (j-1));
            }
        }

        //Al ingresar todos los datos se puede iniciar la simulación y visualizar el Mapa
        this.IniciarSimu.setVisible(true);
        this.verGraph.setVisible(true);

    }//GEN-LAST:event_IngresarValActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        // TODO add your handling code here:
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();

    }//GEN-LAST:event_SalirActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Vista_Principal().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void verGraphActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verGraphActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Para visualizar el grafo primero debe darle"
            + " click izquierdo al mouse para ver los nodos y click derecho para ver los caminos");
        JFrame ventana = new JFrame ();
        int nodos = this.ciudades;
        ventana.add(new Canvas (nodos));
        ventana.setBackground(Color.WHITE);
        ventana.setSize(630,530);
        ventana.setResizable(false);
        ventana.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        ventana.setVisible(true);
    }//GEN-LAST:event_verGraphActionPerformed

    private void NextIteracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextIteracionActionPerformed
        // TODO add your handling code here:

        for (int i = 0; i <grafo.getCiudad(); i++) {
            grafo.getCiudades()[i].setVisitada(false);
        }
        Ciudad ciuElegida;

        for (int j = 0; j <cantHormigas; j++) {
            vectorHor[j].setCiudadesVisitadas(grafo.getCiudades());
            ciuElegida = vectorHor[j].Incio(this.grafo.getCiudades(), this.ciudades);
            vectorHor[j].setCiudadActual(ciuElegida);
            vectorHor[j].Caminar(this.ciudades-1, this.a, this.b, this.grafo.getMatDistancia(), this.grafo.getMatFeromonas(), this.ciudades, this.cantHormigas);
        }
        cantIteraciones -=1;
        vectorHor[0].ActFeromonasIteracion(grafo.getMatFeromonas(), r);

        for (int k = 0; k < grafo.getMatFeromonas().length; k++) {
            for (int l = 0; l < grafo.getMatFeromonas().length; l++) {
                System.out.print(grafo.getMatFeromonas()[k][l]);
            }
            System.out.println("");
        }

        System.out.println("");

        if(cantIteraciones==0){
            NextIteracion.setVisible(false);
        }
    }//GEN-LAST:event_NextIteracionActionPerformed

    private void IniciarSimuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IniciarSimuActionPerformed
        // TODO add your handling code here:
        //
//        Hormiga hormiga;
        vectorHor = new Hormiga [this.cantHormigas];
        for (int i = 0; i <this.cantHormigas; i++) {
            Hormiga hormiga = new Hormiga(this.grafo.getCiudades());
            hormiga.setCiudadesVisitadas(this.grafo.getCiudades());
            vectorHor[i]=hormiga;
        }
        Ciudad ciuElegida;

        for (int j = 0; j < vectorHor.length; j++) {
            ciuElegida = vectorHor[j].Incio(this.grafo.getCiudades(), this.ciudades);
            vectorHor[j].setCiudadActual(ciuElegida);
            vectorHor[j].getCiudadActual().setVisitada(true);
            vectorHor[j].Caminar(ciudades-1, this.a, this.b, grafo.getMatDistancia(), grafo.getMatFeromonas(), this.ciudades, this.cantHormigas);
        }
        
        vectorHor[0].ActFeromonasIteracion(grafo.getMatFeromonas(), r);
        
        NextIteracion.setVisible(true);
    }//GEN-LAST:event_IniciarSimuActionPerformed

    private void distRecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_distRecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_distRecoActionPerformed

    private void numHormigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numHormigaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numHormigaActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
        this.jTextField1.setText(this.cantH);
    }//GEN-LAST:event_jTextField1ActionPerformed

    public void caminarHormigas(){
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista_Grafo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista_Grafo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista_Grafo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista_Grafo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista_Grafo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton IngresarVal;
    private javax.swing.JButton IniciarSimu;
    private javax.swing.JButton NextIteracion;
    private javax.swing.JButton Salir;
    private javax.swing.JTextField cuidadVisi;
    private javax.swing.JTextField distReco;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField numHormiga;
    private javax.swing.JButton verGraph;
    // End of variables declaration//GEN-END:variables
}

